# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-03 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='post.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=160, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post')),
                ('background', models.TextField()),
                ('background_image1', models.ImageField(blank=True, null=True, upload_to='post')),
                ('background_image2', models.ImageField(blank=True, null=True, upload_to='post')),
                ('background_image3', models.ImageField(blank=True, null=True, upload_to='post')),
                ('view_count', models.PositiveSmallIntegerField(default=0)),
                ('share_count', models.PositiveSmallIntegerField(default=0)),
                ('pro_title', models.CharField(max_length=160, null=True)),
                ('con_title', models.CharField(max_length=160, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
