# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_image4',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
        migrations.AddField(
            model_name='post',
            name='background_image5',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
