# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('comment', '0002_auto_20190104_0604'),
        ('post', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='post.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_pro_comments',
            field=models.ManyToManyField(blank=True, related_name='like_pro', to='comment.ProComment'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
