# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-04 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190104_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hate_con_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hate_pro_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_con_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_pro_comments',
        ),
    ]
