# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190105_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', '남성'), ('f', '여성'), ('o', '기타')], max_length=1, null=True),
        ),
    ]
