# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20190125_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
