# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnConComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentOnProComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportConComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('report_reason', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abuse', '심한 욕설을 포함하고 있어요 NO!'), ('infringement', '명예훼손/사생활침해 및 저작권침해!'), ('obscenity', '음란성 또는 청소년에게 매우 유해!'), ('Prosperity', '느닷없는 홍보 게시물 발견!'), ('irrelevant', '의견과 무관한 아무말 대잔치 댓글!')], max_length=50, null=True)),
                ('etc_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportProComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('report_reason', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abuse', '심한 욕설을 포함하고 있어요 NO!'), ('infringement', '명예훼손/사생활침해 및 저작권침해!'), ('obscenity', '음란성 또는 청소년에게 매우 유해!'), ('Prosperity', '느닷없는 홍보 게시물 발견!'), ('irrelevant', '의견과 무관한 아무말 대잔치 댓글!')], max_length=50, null=True)),
                ('etc_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
