# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-04 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tag'),
        ('member', '0003_auto_20190105_0338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_auto_20190104_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('type', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentOnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_comment', to='comment.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('report_reason', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abuse', '심한 욕설을 포함하고 있어요 NO!'), ('infringement', '명예훼손/사생활침해 및 저작권침해!'), ('obscenity', '음란성 또는 청소년에게 매우 유해!'), ('Prosperity', '느닷없는 홍보 게시물 발견!'), ('irrelevant', '의견과 무관한 아무말 대잔치 댓글!')], max_length=50, null=True)),
                ('etc_text', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commentonconcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentonconcomment',
            name='con_comment',
        ),
        migrations.RemoveField(
            model_name='commentonprocomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentonprocomment',
            name='pro_comment',
        ),
        migrations.RemoveField(
            model_name='concomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='concomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='procomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='procomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reportconcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reportconcomment',
            name='con_comment',
        ),
        migrations.RemoveField(
            model_name='reportprocomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reportprocomment',
            name='pro_comment',
        ),
        migrations.DeleteModel(
            name='CommentOnConComment',
        ),
        migrations.DeleteModel(
            name='CommentOnProComment',
        ),
        migrations.DeleteModel(
            name='ConComment',
        ),
        migrations.DeleteModel(
            name='ProComment',
        ),
        migrations.DeleteModel(
            name='ReportConComment',
        ),
        migrations.DeleteModel(
            name='ReportProComment',
        ),
    ]
